= BASE64 Library for Arduino =

Helps to read out essential info from ESP8266.

There are native as well as object oriented functions.

Here is the List of the Native Functions for those who want more Control:

  - `size_t base64_encode(char *output, char *input, size_t inputLen)`

This function helps to Encode the Stream of Bytes provided at the *input* to *output*
User needs to ensure that that the Output buffer is adequacy sized.

  - `size_t base64_decode(char *output, char *input, size_t inputLen)`

This function helps to Decode the Stream ob Bytes provided at the *input* to *output*  
User needs to ensure that that the Output buffer is adequacy sized.

  - `size_t base64_enc_len(size_t inputLen)`
  
This function can be used to ascertain the maximum size of buffer needed to accommodate  
the converted BASE64 output 

  - `size_t base64_decode(char *output, char *input, size_t inputLen)`
  
This function can be used to find out the maximum size of the buffer needed to accommodate  
the converted original string from BASE64


Here is the List of the OO Function in `base64` class:

  - `String BASE64::encode(uint8_t *data, size_t length)` - For Direct byte Stream

  - `String BASE64::encode(char *data)` - For NULL Terminated character Array as shown in the **Example Below**
  
  - `String BASE64::encode(String text)` - String containing the source
  
Function to Convert into BASE64 encoded string else returns the string `"-FAIL"`

  - `String BASE64::decode(uint8_t *data, size_t length)` - For Direct byte Stream
  
  - `String BASE64::decode(char *data)` - For NULL Terminated character Array as shown in the **Example Below**
  
  - `String BASE64::decode(String text)` - String containing the source
  
Function to Convert back from BASE64 encoding else returns the string `"-FAIL"`


== Example ==

```arduino
#include <Base64.h>

void setup() {
  Serial.begin(115200);
}

void loop() {
  Serial.println(base64.encode("Hello There, I am doing Good."));
  Serial.println(base64.decode("SGVsbG8gVGhlcmUsIEkgYW0gZG9pbmcgR29vZC4="));
  delay(2000);
}
```

=== Dependencies ===
 WString Library
 Thread Safe: No
 Extendable: Yes

For more information about this library please visit us at
http://github.com/boseji/BASE64

== License ==

Released Under creative commons license 3.0: Attribution-ShareAlike CC BY-SA

